//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class user
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display (Name = "Username")]
        public string username { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Retype Password")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("password", ErrorMessage = "Passwords do not match, type again")]
        public string confirmpassword { get; set; }

    }
}
